name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn
      - name: Update API reports
        run: mkdir -p api && yarn api-extractor run --local
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update API report as of ${{ github.sha }}
          file_pattern: api
          commit_user_name: rebasecop
          commit_user_email: rebasecop@users.noreply.github.com
          commit_author: rebasecop <rebasecop@users.noreply.github.com>
